from setuptools import setup

setup(
    name='XKCD_archiver',
    version='1.0',
    packages=['downloadXKCD_env.Lib.site-packages.idna', 'downloadXKCD_env.Lib.site-packages.certifi',
              'downloadXKCD_env.Lib.site-packages.chardet', 'downloadXKCD_env.Lib.site-packages.chardet.cli',
              'downloadXKCD_env.Lib.site-packages.urllib3', 'downloadXKCD_env.Lib.site-packages.urllib3.util',
              'downloadXKCD_env.Lib.site-packages.urllib3.contrib',
              'downloadXKCD_env.Lib.site-packages.urllib3.contrib._securetransport',
              'downloadXKCD_env.Lib.site-packages.urllib3.packages',
              'downloadXKCD_env.Lib.site-packages.urllib3.packages.backports',
              'downloadXKCD_env.Lib.site-packages.urllib3.packages.ssl_match_hostname',
              'downloadXKCD_env.Lib.site-packages.requests',
              'downloadXKCD_env.Lib.site-packages.pip-9.0.1-py3.6.egg.pip',
              'downloadXKCD_env.Lib.site-packages.pip-9.0.1-py3.6.egg.pip.req',
              'downloadXKCD_env.Lib.site-packages.pip-9.0.1-py3.6.egg.pip.vcs',
              'downloadXKCD_env.Lib.site-packages.pip-9.0.1-py3.6.egg.pip.utils',
              'downloadXKCD_env.Lib.site-packages.pip-9.0.1-py3.6.egg.pip.compat',
              'downloadXKCD_env.Lib.site-packages.pip-9.0.1-py3.6.egg.pip.models',
              'downloadXKCD_env.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor',
              'downloadXKCD_env.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.distlib',
              'downloadXKCD_env.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.distlib._backport',
              'downloadXKCD_env.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.colorama',
              'downloadXKCD_env.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib',
              'downloadXKCD_env.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib._trie',
              'downloadXKCD_env.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.filters',
              'downloadXKCD_env.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.treewalkers',
              'downloadXKCD_env.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.treeadapters',
              'downloadXKCD_env.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.treebuilders',
              'downloadXKCD_env.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.lockfile',
              'downloadXKCD_env.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.progress',
              'downloadXKCD_env.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests',
              'downloadXKCD_env.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages',
              'downloadXKCD_env.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.chardet',
              'downloadXKCD_env.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3',
              'downloadXKCD_env.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.util',
              'downloadXKCD_env.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.contrib',
              'downloadXKCD_env.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.packages',
              'downloadXKCD_env.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'downloadXKCD_env.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.packaging',
              'downloadXKCD_env.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.cachecontrol',
              'downloadXKCD_env.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.cachecontrol.caches',
              'downloadXKCD_env.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.webencodings',
              'downloadXKCD_env.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.pkg_resources',
              'downloadXKCD_env.Lib.site-packages.pip-9.0.1-py3.6.egg.pip.commands',
              'downloadXKCD_env.Lib.site-packages.pip-9.0.1-py3.6.egg.pip.operations'],
    url='',
    license='',
    author='David Antonini // toonarmycaptain',
    author_email='toonarmycaptain@hotmail.com',
    description='v1.0 XKCD_archiver'
)
